version: 2

sources:
  - name: _airbyte_raw
    database: test_db
    schema: airbyte
    tables:
      - name: _airbyte_raw_books

models:
  - name: transform_books
    description: "A model to transform raw airbyte dumped table into books table"
