version: 2

sources:
  - name: _airbyte_raw
    database: test_db
    schema: airbyte
    tables:
      - name: _airbyte_raw_form_responses_1

models:
  - name: transfrom_form_respones
    description: "A model to transform raw airbyte form responses data in json form into tabular form"
