version: 2

sources:
  - name: _airbyte_raw
    database: test_db
    schema: airbyte
    tables:
      - name: _airbyte_raw_form_responses_1

models:
  - name: test_fruits
    description: "A test model for fruits"
